### ISSUE TITLE
Failing test, despite returning the expected array

### ISSUE THREAD

**Issue by markjwee** [learn-co-curriculum/phase-1-array-map-method-lab#7]
### Canvas Link

https://learning.flatironschool.com/courses/4608/assignments/149904?module_item_id=317645

### Concern

I have confirmed that the return for titleCased() matches the expected array, by running in Replit and Chrome dev tool. But the code does not pass the test and and I get TypeError: Cannot read properties of undefined (reading 'map')

### My code:
    function titleCased(array) {
      const titleCasedArray = array.map(titleCaseString)
      return titleCasedArray;
    }
    
    function titleCaseString(string) {
      let titleCasedString = ""
      let words = string.split(" ");
      for (let i = 0; i < words.length; i++) {
        words[i] = words[i][0].toUpperCase() + words[i].substr(1);
      }
      titleCasedString = words.join(" ");
      return titleCasedString;
    }

### Error:

     TypeError: Cannot read properties of undefined (reading 'map')
      at titleCased (about:blank:4:31)
      at Context.<anonymous> (test/indexTest.js:4:14)

**Comment by ihollander** [comment]
Hi @markjwee - thanks for your feedback! It looks like your logic is correct, but you've written the function to accept a parameter, and the test doesn't pass any arguments to the function during testing. We'll update the instructions to make this clear.
